// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "dende.proto" (package "dende", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * The main message wrapping a drawing action
 *
 * @generated from protobuf message dende.DendePart
 */
export interface DendePart {
    /**
     * @generated from protobuf field: dende.DendePart.PartType type = 1
     */
    type: DendePart_PartType;
    /**
     * @generated from protobuf field: bool is_line_end = 2
     */
    isLineEnd: boolean;
    /**
     * @generated from protobuf field: repeated int32 coordinates = 3
     */
    coordinates: number[]; // [x1, y1, x2, y2, ...]
    /**
     * @generated from protobuf field: dende.Color color = 4
     */
    color?: Color;
    /**
     * @generated from protobuf field: float line_width = 5
     */
    lineWidth: number;
}
/**
 * @generated from protobuf enum dende.DendePart.PartType
 */
export enum DendePart_PartType {
    /**
     * @generated from protobuf enum value: DRAWING = 0;
     */
    DRAWING = 0,
    /**
     * @generated from protobuf enum value: FILLING = 1;
     */
    FILLING = 1,
    /**
     * @generated from protobuf enum value: UNDO = 2;
     */
    UNDO = 2,
    /**
     * @generated from protobuf enum value: REDO = 3;
     */
    REDO = 3,
    /**
     * @generated from protobuf enum value: CLEAR = 4;
     */
    CLEAR = 4
}
/**
 * @generated from protobuf message dende.Color
 */
export interface Color {
    /**
     * @generated from protobuf field: int32 r = 1
     */
    r: number;
    /**
     * @generated from protobuf field: int32 g = 2
     */
    g: number;
    /**
     * @generated from protobuf field: int32 b = 3
     */
    b: number;
    /**
     * @generated from protobuf field: float a = 4
     */
    a: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class DendePart$Type extends MessageType<DendePart> {
    constructor() {
        super("dende.DendePart", [
            { no: 1, name: "type", kind: "enum", T: () => ["dende.DendePart.PartType", DendePart_PartType] },
            { no: 2, name: "is_line_end", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "coordinates", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "color", kind: "message", T: () => Color },
            { no: 5, name: "line_width", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<DendePart>): DendePart {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.type = 0;
        message.isLineEnd = false;
        message.coordinates = [];
        message.lineWidth = 0;
        if (value !== undefined)
            reflectionMergePartial<DendePart>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DendePart): DendePart {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* dende.DendePart.PartType type */ 1:
                    message.type = reader.int32();
                    break;
                case /* bool is_line_end */ 2:
                    message.isLineEnd = reader.bool();
                    break;
                case /* repeated int32 coordinates */ 3:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.coordinates.push(reader.int32());
                    else
                        message.coordinates.push(reader.int32());
                    break;
                case /* dende.Color color */ 4:
                    message.color = Color.internalBinaryRead(reader, reader.uint32(), options, message.color);
                    break;
                case /* float line_width */ 5:
                    message.lineWidth = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DendePart, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* dende.DendePart.PartType type = 1; */
        if (message.type !== 0)
            writer.tag(1, WireType.Varint).int32(message.type);
        /* bool is_line_end = 2; */
        if (message.isLineEnd !== false)
            writer.tag(2, WireType.Varint).bool(message.isLineEnd);
        /* repeated int32 coordinates = 3; */
        if (message.coordinates.length) {
            writer.tag(3, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.coordinates.length; i++)
                writer.int32(message.coordinates[i]);
            writer.join();
        }
        /* dende.Color color = 4; */
        if (message.color)
            Color.internalBinaryWrite(message.color, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* float line_width = 5; */
        if (message.lineWidth !== 0)
            writer.tag(5, WireType.Bit32).float(message.lineWidth);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message dende.DendePart
 */
export const DendePart = new DendePart$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Color$Type extends MessageType<Color> {
    constructor() {
        super("dende.Color", [
            { no: 1, name: "r", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "g", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "b", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "a", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
    create(value?: PartialMessage<Color>): Color {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.r = 0;
        message.g = 0;
        message.b = 0;
        message.a = 0;
        if (value !== undefined)
            reflectionMergePartial<Color>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Color): Color {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 r */ 1:
                    message.r = reader.int32();
                    break;
                case /* int32 g */ 2:
                    message.g = reader.int32();
                    break;
                case /* int32 b */ 3:
                    message.b = reader.int32();
                    break;
                case /* float a */ 4:
                    message.a = reader.float();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Color, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 r = 1; */
        if (message.r !== 0)
            writer.tag(1, WireType.Varint).int32(message.r);
        /* int32 g = 2; */
        if (message.g !== 0)
            writer.tag(2, WireType.Varint).int32(message.g);
        /* int32 b = 3; */
        if (message.b !== 0)
            writer.tag(3, WireType.Varint).int32(message.b);
        /* float a = 4; */
        if (message.a !== 0)
            writer.tag(4, WireType.Bit32).float(message.a);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message dende.Color
 */
export const Color = new Color$Type();
